### ISSUE TITLE
[PROPOSAL] Logout option

### ISSUE THREAD

**Issue by Ankitkumar94** [alchemsynergy/alchem#21]
Logout option/button should be added in the user settings drawer.

**Comment by anirudhreddy1997** [comment]
hi,
I added logout option in mainstage as a button.
is it ok.

**Comment by techfreakworm** [comment]
@anirudhreddy1997 where exactly? It should be in   navigation drawer which displays user info.

**Comment by anirudhreddy1997** [comment]
![capture](https://user-images.githubusercontent.com/16227867/33937918-551254ea-e02b-11e7-807a-834f7372445a.PNG)
It appears below user info option and above settings option.
